### PR TITLE
Fix: carrot pill by refactoring getBestApyPairCampaign

### LINKED ISSUE #1579: Carrot pill in incorrectly ON
**Description**
The UI says there are Carrot rewards in a campaign but there are none. Not too sure if this lights up even for expired carrot campaigns.

**How to Reproduce**
Goto https://swapr.eth.limo/#/pools?chainId=100 and is also on the build from develop branch.

**Expected behavior**
If there are active Carrot farming campaigns, Carrot pill should light up. Else, it should look disabled.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by Diogomartf**
# Summary

Fixes #1579

Refactor `getBestApyPairCampaign` function.
- improve variables names
- only return currentCampaign if the APY is greater. 
- added checks to see if campaign did not launch yet
- Add check to see if campaign is already closed.

image
image

  # To Test

1. Go to liquidity pools
- [ ] Check if carrot pill  highlight is correct.

  # Background

*Optional: Give background information for changes you've made, that might be difficult to explain via comments*

### CODE REVIEW

**Comment by 0xVenky** [comment]
LGTM 🚀  :)

**Comment by MilanVojnovic95** [comment]
Tested and looks ok to me 👍

**Review by berteotti — APPROVED** [review]

**Comment by Mi-Lan** [comment]
Screenshot 2022-11-23 at 17 58 47
Hmm I still see it...

**Comment by Diogomartf** [comment]
> Screenshot 2022-11-23 at 17 58 47 Hmm I still see it...

Yeah, thanks for noticing.  As I was improving the variables names and code I messed up in a signal on `currentCampaignIsOpen`. I think now is good.

image

**Review by Mi-Lan — APPROVED** [review]
Looks good!

**Pull request merged**
