### PR TITLE
fix: adjust balance and stake accordingly to the design

### LINKED ISSUE #743: Balance and stake wrong size
See design for correct size
https://www.figma.com/file/L8tamoiv3mTCRaypHLk1us/DXswap?node-id=7213%3A31504

### PR DESCRIPTION
**Pull request by guerrap**
# Summary

Fixes #743 

Adjust size for balance and stake.

before:
image
after:
image

 # To Test

1. On any page
- [ ] Verify that balance and stake have the right size

### CODE REVIEW

**Comment by Mi-Lan** [comment]
Hmm it seems not to have latest code from develop which includes the gas indicator can you pull it and make sure that gas indicator also has correct sizing...

**Comment by guerrap** [comment]
Adjusted the size to include the gas component
image

**Comment by niemam29** [comment]
On mobile side, option to switch to other page disappeared.
#### How it looks before
cache

#### How it looks now
cache

**Review by berteotti — APPROVED** [review]
Good fix!

**Comment by MilanVojnovic95** [comment]
@guerrap 
It seems to me that there is Miss-alignment numbers and text in the fields ( not centered ).
Does not include gas indicator.
image
can you also make a fix for that?

**Comment by guerrap** [comment]
I have adjusted the `line-height` and the `max-height` of the `Amount` component in order to correctly align the text inside.

**Review by Mi-Lan — APPROVED** [review]
LGTM!

**Comment by MilanVojnovic95** [comment]
Tested and looks ok to me.

**Pull request merged**
