### PR TITLE
Xdai shows on Bridge currency list

### LINKED ISSUE #1354: Xdai is not showing up when searching for it in bridge
**Description**
Xdai is not showing up when searching for it in bridge

#### Definition of done
- [ ] Description is created (Task creator)
- [ ] Code is complete (Developer)
- [ ] Scope of test and what was done section is defined in task (Developer)
- [ ] Review passed (Code reviewer)
- [ ] Verified manually (QA)
- [ ] Test cases created/updated if necessary (QA)
- [ ] Change successfully merged
- [ ] Release notes added if needed

**How to Reproduce**
1. Go to bridge
2. Select gnosis to polygon
3. Click on select token
4. Type xdai

**Recording**

https://images.zenhubusercontent.com/209400598/b0047f02-c0b5-4f90-a39b-3048de6848d0/s.mp4

### PR DESCRIPTION
**Pull request by Mi-Lan**
closes #1354 
- In this pr I disabled token select when pairs are not supported and added a message for invalid chain
Screenshot 2022-09-08 at 15 24 30
- And native pairs will show
- Also dried up code a bit for bridge stuff

### CODE REVIEW

**Review by mix1o — COMMENTED** [review]
user can select `XDAI` while bridging from `Gnosis` to `Testnet`
image
image

**Comment by Mi-Lan** [comment]
> user can select `XDAI` while bridging from `Gnosis` to `Testnet` image image

@mix1o Hey men wondering whats the point of having option to select bridge which can't be bridged to? Should we make it disabled?

**Comment by mix1o** [comment]
> > user can select `XDAI` while bridging from `Gnosis` to `Testnet` image image
> 
> @mix1o Hey men wondering whats the point of having option to select bridge which can't be bridged to? Should we make it disabled?

Basically user won't see any bridge but I think we should change button text and inform user that he selected incorrect chains
image

**Review by mix1o — APPROVED** [review]

**Comment by MilanVojnovic95** [comment]
Tested and looks ok to me 👍 
It showing XDAI when you searching it for the bridge and also if it is impossible to bridge from one to another network it
shows message "INVALID CHAIN PAIR" 👍

**Review by berteotti — APPROVED** [review]
Good job!

**Pull request merged**
