### PR TITLE
feat(walletModal): replace footer banner

### LINKED ISSUE #1164: Connect modal. DXdao banner
New design for "a dxdao product" thingy in the connect modal. I have long been not happy with the old design. This is a modal every user sees. Not sure why it never got finished for the design i had. 

Anyways i made a new one that is a bit more colorful and should highlight that this is a dxdao product. The banner is clickable and should link to dxdao landing page.

Use the SVG to apply the new banner. Dont make it in code.

SVG for the banner 

Link to the design 
https://www.figma.com/file/sh1SahVJbRgCk2kIrxNgyG/Swapr-1.5?node-id=433%3A5425

### PR DESCRIPTION
**Pull request by 0xVance**
# Summary

Resolves #1164

### CODE REVIEW

**Comment by niemam29** [comment]
Tested and looks good to me

**Review by mix1o — APPROVED** [review]

**Comment by wixzi** [comment]
@0xVenky Do we need dxdao.eth.limo in the text also?

**Review by wixzi — APPROVED** [review]
LGTM 🥇

**Comment by wixzi** [comment]
Optimized svg

DxDaoProductBanner

Suggest to optimize the svg and use it
https://jakearchibald.github.io/svgomg/

**Comment by 0xVance** [comment]
> Optimized svg
> 
> DxDaoProductBanner
> 
> Suggest to optimize the svg and use it https://jakearchibald.github.io/svgomg/
> 
> Screenshot 2022-09-19 at 16 40 28

@zamli @0xVenky are you okay with optimization? I'm not feeling authorized to make such decision :)

**Comment by 0xVance** [comment]
> @0xVenky Do we need dxdao.eth.limo in the text also?

I know only as much as stated in #1164. I assume that it's not required.

**Review by Diogomartf — APPROVED** [review]

**Comment by berteotti** [comment]
> @zamli @0xVenky are you okay with optimization? I'm not feeling authorized to make such decision :)

Optimizing the SVG will not impact the SVG quality so I think it's better to optimize it, so we can save some space :)

**Comment by berteotti** [comment]
> > @0xVenky Do we need dxdao.eth.limo in the text also?
> 
> I know only as much as stated in #1164. I assume that it's not required.

I don't think we should pick a desired resolver. People can access use through .limo, .link or any new resolver that appears on the market. We like decentralization!

**Comment by 0xVance** [comment]
> Optimized svg
> 
> DxDaoProductBanner
> 
> Suggest to optimize the svg and use it https://jakearchibald.github.io/svgomg/
> 
> Screenshot 2022-09-19 at 16 40 28

I updated svg with optimized version, thanks for resource!

**Pull request merged**
