### PR TITLE
test: remove USD Price hook

### PR DESCRIPTION
**Pull request by adamazad**
# Summary

Removes the USD price hook to check if it indeed causes the memory leak and lag. **This is an experimental PR and not intended for merging**.

### CODE REVIEW

**Comment by MilanVojnovic95** [comment]
Tested and it seems much better to me, lagging is still present but very little sometimes 👍

**Comment by adamazad** [comment]
@berteotti can you revist `useUSDValue` and related hooks to fix this leak? Happy to collaborate and help.

**Comment by berteotti** [comment]
> @berteotti can you revist `useUSDValue` and related hooks to fix this leak? Happy to collaborate and help.

Sure, will do it ASAP.

**Comment by adamazad** [comment]
Closing in favor of #1067

**Pull request closed without merging**
