### PR TITLE
Feature/eco bridge reducer cleanup

### PR DESCRIPTION
**Pull request by mix1o**
# Summary

### 1. First step of cleanup

When we were implementing `ecoBridge` we created `reducer` for each bridge. The problem was the part of code was exactly the same in each bridge.

So in this pr we implemented something like: `createEcoBridgeChildBaseSlice` and we put there repeated code.

#### We moved all those functions:
- `requestStarted`
- `setBridgeDetails`
- `setBridgeDetailsStatus`
- `setTokenListsStatus`
- `addTokenLists`
 #### to one slice and we are using it across bridges.

### 2. Second step of cleanup
In `EcoBridge` we added  `ecoBridgeUtils` object which keeps useful methods:
- ui - manages state of `modal` and `button`
- `logger` - for debugging or throwing errors you can use custom logger inside `ecoBridge`
- `metadataStatus` - easy way to handle `getBridgingMetadata` function
- `listeners` - now `ecoBridge` handles `pendingTransacitonsListeners` for each bridge

# To Test
#### NOTE: This pr shouldn't affect any bridge. It only improves code quality

1. Open `Bridge` page
2. Do transaction through all available bridges
3. Check if flow is the same

### CODE REVIEW

**Review by berteotti — APPROVED** [review]
Code looks fine to me. It would be nice to have another code review apart from mine.

**Comment by MilanVojnovic95** [comment]
Tested, it happens that after the first network change in the bridge section, that it will not react when you click on the field to change the network, and it is possible only by changing the network from the wallet...

image

I also tested locally the tests that failed and it happened randomly everything is ok when I test manually...

**Comment by Diogomartf** [comment]
> Tested, it happens that after the first network change in the bridge section, that it will not react when you click on the field to change the network, and it is possible only by changing the network from the wallet...
> 
> image
> 
> I also tested locally the tests that failed and it happened randomly everything is ok when I test manually...

Tested both locally and in the preview and wasn't able to reproduce the network switch error you've mentioned. @MilanVojnovic95 if could tell the steps to reproduce it. 🙌

**Comment by MilanVojnovic95** [comment]
> > Tested, it happens that after the first network change in the bridge section, that it will not react when you click on the field to change the network, and it is possible only by changing the network from the wallet...
> > image
> > I also tested locally the tests that failed and it happened randomly everything is ok when I test manually...
> 
> Tested both locally and in the preview and wasn't able to reproduce the network switch error you've mentioned. @MilanVojnovic95 if you could tell the steps to reproduce it. 🙌

Retested and looks ok to me 👍

**Comment by MilanVojnovic95** [comment]
Retested and looks ok to me 👍

**Pull request merged**
