### PR TITLE
fix: show usd price when trading via uniswap

### LINKED ISSUE #1161: No dolar value for assets when swapping through uniswap
**Description**
Dolar value is not showing up when swapping through uniswap

#### Definition of done
- [ ] Description is created (Task creator)
- [ ] Code is complete (Developer)
- [ ] Scope of test and what was done section is defined in task (Developer)
- [ ] Review passed (Code reviewer)
- [ ] Verified manually (QA)
- [ ] Test cases created/updated if necessary (QA)
- [ ] Change successfully merged
- [ ] Release notes added if needed

**Screenshots**

### PR DESCRIPTION
**Pull request by berteotti**
# Summary

Fixes #1161

Show usd price when trading via uniswap. This is an hotfix.

image

  # To Test

1.  Open the page `swap`
2. Simulate a trade with Uniswap selected
- [ ] Verify USD price appears under the output token

### CODE REVIEW

**Comment by MilanVojnovic95** [comment]
Tested and looks ok to me 👍

**Review by Diogomartf — APPROVED** [review]

**Comment by jorgedclopes** [comment]
Something is def. wrong.
I tried to test this deployment and... When I try to simulate a trade it keeps trying to recompute and replace the output.

**Comment by berteotti** [comment]
> Something is def. wrong. I tried to test this deployment and... When I try to simulate a trade it keeps trying to recompute and replace the output.

Yeah, it's a known bug in develop branch being fixed now :)

**Review by jorgedclopes — APPROVED** [review]

**Comment by MilanVojnovic95** [comment]
Tested and looks ok to me 👍

**Pull request merged**
