### PR TITLE
[Feature] EcoRouter show more markets button

### LINKED ISSUE #643: More markets

### PR DESCRIPTION
**Pull request by berteotti**
# Summary

Closes #643

Add EcoRouter platform list show more markets button.

Screenshot 2022-04-04 at 13 24 06

  # To Test

1. Open the page `swap`
2. Choose a trading pair with more than 3  available markets
- [ ] Shows only 3 markets
- [ ] Shows button "Show more"
3. Click in "Show more"
- [ ] Should show every market
- [ ] Button disappears

### CODE REVIEW

**Comment by MilanVojnovic95** [comment]
@berteotti 
Tested and there is a thing that I think is not good and that is that if you click on "Show more" on the first pair for swap then will be shown more then 3 markets on every next pair that you choose.

Shouldn't it show only 3 markets on each newly selected pair and always have the "Show more" option?

In this case you can click "Show more" only once and then on each next pair you have more than 3 markets displayed.

**Comment by zamli** [comment]
What we could do is to have the routes reset every time price changes or tokens changed.

**Comment by MilanVojnovic95** [comment]
@berteotti 
Tested and now looks ok.
But I found a new bug, try reproducing this by image with the same pair on Gnosis network
image

**Comment by niemam29** [comment]
Looks good besides issue founded by @MilanVojnovic95

**Comment by 0xVenky** [comment]
Looks good to me! :) Great job @berteotti

**Comment by berteotti** [comment]
> @berteotti Tested and now looks ok. But I found a new bug, try reproducing this by image with the same pair on Gnosis network image

Can you retest it please? Think it's fixed now!

**Comment by MilanVojnovic95** [comment]
@berteotti 
Retested and now we have this symbol but only on this pair
image

**Comment by berteotti** [comment]
> @berteotti Retested and now we have this symbol but only on this pair image

As there is very low liquidity on that pair on Sushi, there token received are very low. As we can't show many decimal places we are showing only value above 0.000001, everything lower than that we show <0.000001. As you can see in the screenshot below Sushi minimum received is very low.

Screenshot 2022-04-08 at 11 29 38

**Comment by berteotti** [comment]
> > @berteotti Retested and now we have this symbol but only on this pair image

> We can't show many decimal places we are showing only value above 0.000001, everything lower than that we show <0.000001. As you can see in the screenshot below Sushi minimum received is very low.
> 
> Screenshot 2022-04-08 at 11 29 38

**Pull request merged**
