### PR TITLE
fix: Added all native currencies to the max input check

### LINKED ISSUE #1038: Max value in swap does not include gas fee's on Gnosis Chain and Polygon
**Description**
When user clicks on Max value for some native asset either on Gnosis or Polygon it would not subtract the amount of expected gas fee from the max value and due to that transaction is impossible to accept

#### Definition of done
- [X] Description is created (Task creator)
- [ ] Code is complete (Developer)
- [ ] Scope of test and what was done section is defined in task (Developer)
- [ ] Review passed (Code reviewer)
- [ ] Verified manually (QA)
- [ ] Test cases created/updated if necessary (QA)
- [ ] Change successfully merged
- [ ] Release notes added if needed

**Screenshots**

### PR DESCRIPTION
**Pull request by Mi-Lan**
closes #1038 
I can add custom min amount for each network... but I think its overkill...

### CODE REVIEW

**Review by jorgedclopes — APPROVED** [review]
Might as well change `minimumETHLeft` for `minimumNativeLeft`
Non-blocking.

**Comment by niemam29** [comment]
For 0x on Polygon I still got the problem with insufficient balance, but it's much better. From my side it's good to go

**Comment by MilanVojnovic95** [comment]
Tested on Gnosis and Polygon, and as Kacper mentioned only on Ox we have problem.
I agree it's good enough to go 👍 
But how much effort is needed to fix that as well?

**Review by berteotti — APPROVED** [review]

**Comment by 0xVenky** [comment]
Looks good to me!

**Pull request merged**
