### PR TITLE
bugfix: remove static provider in eco router

### PR DESCRIPTION
**Pull request by adamazad**
# Summary

~~Adds `http` protocol to `StaticJsonRpcProvider` instance.~~ Removes static provider condition.

### CODE REVIEW

**Review by berteotti — APPROVED** [review]
Code LGTM!

**Review by berteotti — APPROVED** [review]

**Review by Diogomartf — APPROVED** [review]

**Comment by Mi-Lan** [comment]
@adamazad Can you give me some time to test this. I think this can cause some issues in the sdk...

**Review by Mi-Lan — APPROVED** [review]
Looks good!

**Comment by niemam29** [comment]
Tested and looks good to me!

**Pull request merged**
