### PR TITLE
fix: fix infinite loop update in useAutoMaxBalance hook

### LINKED ISSUE #1240: Error: Maximum update depth exceeded in `useAutoMaxBalance` hook
**Description**

in `src/hooks/useAutoMaxBalance.ts:15`

https://github.com/levelkdev/swapr-dapp/blob/b7f4e110239a9a719d16dd843abc5a396ff11b15/src/hooks/useAutoMaxBalance.ts#L10-L29

Which was added in #1013

image

#### Definition of done
- [ ] Description is created (Task creator)
- [ ] Code is complete (Developer)
- [ ] Scope of test and what was done section is defined in task (Developer)
- [ ] Review passed (Code reviewer)
- [ ] Verified manually (QA)
- [ ] Test cases created/updated if necessary (QA)
- [ ] Change successfully merged
- [ ] Release notes added if needed

**How to Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
Also, if it's relevant for the described byg, add information like the browser or OS.

### PR DESCRIPTION
**Pull request by berteotti**
# Summary

Fixes #1240

Fix infinite loop update in useAutoMaxBalance hook.

  # To Test

1. Open the page `swap`
2. Click on max balance
3. Choose another token
- [ ] App doesn't crash
- [ ] New token max balance should be displayed

### CODE REVIEW

**Review by Diogomartf — APPROVED** [review]

**Comment by niemam29** [comment]
Hey! I spotted some problems - the input is kinda laggy when calculacting the price and also sometimes when the max value is taken for the other input. (Both of those problems can be spotted in the recording)

https://user-images.githubusercontent.com/30408272/178774293-ad940f74-8d1c-4108-ac2b-b80b3f154f50.mp4

**Comment by berteotti** [comment]
> Hey! I spotted some problems - the input is kinda laggy when calculacting the price and also sometimes when the max value is taken for the other input. (Both of those problems can be spotted in the recording)

Hey! This happens because you clicked max balance in both inputs, so if you change one of the tokens, the input where you changed will trigger max balance. Should we have a shared state between the 2 inputs?

**Comment by niemam29** [comment]
> > Hey! I spotted some problems - the input is kinda laggy when calculacting the price and also sometimes when the max value is taken for the other input. (Both of those problems can be spotted in the recording)
> 
> Hey! This happens because you clicked max balance in both inputs, so if you change one of the tokens, the input where you changed will trigger max balance. Should we have a shared state between the 2 inputs?

I would expect to get max balance from the latest max balance that i clicked, soo if i'd if my last click on max balance would be on the "from" input then after changing tokens it should always get the max value in the "from" input. 
Also this is just a suggestion, it may be resolved in a different way

**Comment by karczuRF** [comment]
Got the same problem which @niemam29 mentioned above, so would be good to create new issue for that indeed. 
I wasn't able to reproduce the problem with infinite loop though, which this PR fixes, so lgtm.

**Comment by niemam29** [comment]
> @niemam29 Can you check the lagging again please? About your suggestion, can you create an issue so we can address it in another PR please?

Still a bit laggy for me, but it's better than before. I would say that this is acceptable.

I will create another pr for this max balances

**Pull request merged**
