### PR TITLE
add socketscan to getExplorerLink function

### PR DESCRIPTION
**Pull request by mix1o**
# Summary

Add SocketScan

# To Test
1. Open `Bridge` page
2. Do transaction through `Socket`
3. If transaction is completed, click on `fromChainId`
4. It should redirect user to `https://socketscan.io/`
5. Check it on `Dashboard` as well

NOTE: Socketscan currently only supports search using source transaction hash.

### CODE REVIEW

**Comment by niemam29** [comment]
Overall looks good but i have one question - link in dashboard shouldn't be replaced with this socketscan too? @0xVenky

**Comment by 0xVenky** [comment]
> 

Yea, I think it makes sense to replace it everywhere

**Review by Diogomartf — APPROVED** [review]

**Review by karczuRF — APPROVED** [review]

**Comment by niemam29** [comment]
Socketscan do not support the second hash from bridge and if user in dashboard click on the second chain it will redirect to socketscan page saying that this tx do not exist - maybe we should leave the gnosis scan here? Or at least use the same hash 
@0xVenky 
cach2

**Comment by niemam29** [comment]
lgtm

**Pull request merged**
