### PR TITLE
Feature/#1139 randomize dex names

### LINKED ISSUE #1139: Randomize dex names for each network for button loader
**Description**
Randomize dex names for each network for button loader. 

#### Definition of done
- [x] Description is created (Task creator)
- [x] Code is complete (Developer)
- [x] Scope of test and what was done section is defined in task (Developer)
- [ ] Review passed (Code reviewer)
- [ ] Verified manually (QA)
- [ ] Test cases created/updated if necessary (QA)
- [ ] Change successfully merged
- [ ] Release notes added if needed

**How to Reproduce**
Always the dex name is same at start of the loading button and that's not optimal.

**Expected behavior**
dex names in loader should be random each time

### PR DESCRIPTION
**Pull request by wixzi**
# Summary

Fixes #1139

Fixes: 
1. Randomize the Dexes in loading button
2. COW was not added in the loading list

Screenshot 2022-07-04 at 17 33 49

  # To Test

1. COW dex should be added in the loading button
2. Loading button Dexes should be shuffled in each loading

### CODE REVIEW

**Comment by wixzi** [comment]
@MilanVojnovic95 Can you give it a try :)

**Review by adamazad — APPROVED** [review]

**Comment by MilanVojnovic95** [comment]
COW dex is added to loading button and dexes are shuffled in each loading
but if you increase the number after the first result then it does not show the loading button but "price impact too high"

https://user-images.githubusercontent.com/57331244/177217639-57a76ad4-1128-40a2-94f5-b278cc05f409.mp4

**Comment by wixzi** [comment]
> COW dex is added to loading button and dexes are shuffled in each loading but if you increase the number after the first result then it does not show the loading button but "price impact too high"
> 
>  Swapr.04.07.mp4

I think that is an existing bug. Not caused by this change. Can you create a new issue for this?

**Comment by wixzi** [comment]
> There is some problem with scaling (Iphone 12 pro) cach2

I will create a bug and fix this

**Pull request merged**
