### PR TITLE
Fix: 1343 set only on mobile smaller logo and bigger gap for settings

### LINKED ISSUE #1343: "Expeditions" button is overlapping on mobile
**Description**
"Expeditions" button is overlapping on IPhone 12 Pro and others 

#### Definition of done
- [x] Description is created (Task creator)
- [x] Code is complete (Developer)
- [ ] Scope of test and what was done section is defined in task (Developer)
- [ ] Review passed (Code reviewer)
- [ ] Verified manually (QA)
- [ ] Test cases created/updated if necessary (QA)
- [ ] Change successfully merged
- [ ] Release notes added if needed

**Screenshots**

### PR DESCRIPTION
**Pull request by mwiniarsk**
# Summary

Fixes #1343 

Set for mobile smaller logo and bigger gap for the settings

Selection_190

  # To Test

1. Open any page where 'Expeditions' button is displayed
2. Check mobile design if button is not overlapping logo

### CODE REVIEW

**Review by adamazad — APPROVED** [review]

**Comment by niemam29** [comment]
Tested and looks good to me! If this is urgent please merge it before evening soo i can do the regression tests before release

**Comment by adamazad** [comment]
> Tested and looks good to me! If this is urgent please merge it before evening soo i can do the regression tests before release

Yes @niemam29. This is planned to be in the next release.

**Comment by mwiniarsk** [comment]
> > Tested and looks good to me! If this is urgent please merge it before evening soo i can do the regression tests before release
> 
> Yes @niemam29. This is planned to be in the next release.

Do you mean the closest release or the one after it? :smile:

**Comment by adamazad** [comment]
> > > Tested and looks good to me! If this is urgent please merge it before evening soo i can do the regression tests before release
> > 
> > 
> > Yes @niemam29. This is planned to be in the next release.
> 
> Do you mean the closest release or the one after it? 😄

Beta 15, sorry for the confusion 😅

**Comment by mwiniarsk** [comment]
> I would suggest maybe increasing gap to 18px so it doesn't overlap at all like this. But if @zamli object leave it as it Screenshot 2022-08-09 at 14 14 03

I put this spacing, as I don't want to have a bigger one on the right side. But yes, I can change it :smiling_face_with_tear:

**Comment by Mi-Lan** [comment]
> > I would suggest maybe increasing gap to 18px so it doesn't overlap at all like this. But if @zamli object leave it as it Screenshot 2022-08-09 at 14 14 03
> 
> I put this spacing, as I don't want to have a bigger one on the right side. But yes, I can change it 🥲

Maybe it can be for just extra small screens not sure about breakpoints....

**Comment by niemam29** [comment]
Retested and looks good!

**Pull request merged**
