### PR TITLE
fix: fix swap button messages

### PR DESCRIPTION
**Pull request by berteotti**
# Summary

Fixes swap button message

 # To Test

1. Simulate a trade
- [ ] Verify swap button contains translated text

### CODE REVIEW

**Comment by wixzi** [comment]
Why are you not putting translated messages ?

**Comment by berteotti** [comment]
> Why are you not putting translated messages ?

I can translate messages but I don't know if I'm making a good translation. I can know it if I translate to portuguese, otherwise I can only copy paste from google translate. So, I think that we need to define how we translate messages. I would prefer some native/professional translator to do it (e.g. some one from the community).

**Review by Diogomartf — APPROVED** [review]

**Review by wixzi — APPROVED** [review]

**Comment by MilanVojnovic95** [comment]
According to google translator, it seems to me that it translates well, however, the application crashes after several translations and clicking on certain buttons.

**Comment by niemam29** [comment]
There is missing whitespace in connect wallet button
cach2

**Comment by niemam29** [comment]
Tested and looks good to me

**Comment by MilanVojnovic95** [comment]
Tested and looks ok to me 👍

**Pull request merged**
