### PR TITLE
[Feautre] Add max balance to output token

### PR DESCRIPTION
**Pull request by berteotti**
# Summary

Add max balance to output token when clicking on balance.

https://user-images.githubusercontent.com/23079677/163380387-1133127c-9c0b-449a-be26-e7fb0460f66b.mp4

# To Test

1.  Open the page `swap`
2. Simulate trade
3. Click in output token max balance
- [ ] Verify the output field is filled with the max balance amount

### CODE REVIEW

**Comment by MilanVojnovic95** [comment]
This so far that I have tested seems ok to me. However it is very slow and it seems to me that lag is very present. 
I know that sometimes it happens, but now it happens to such an extent that it is almost impossible to test.

**Review by adamazad — APPROVED** [review]

**Comment by berteotti** [comment]
> This so far that I have tested seems ok to me. However it is very slow and it seems to me that lag is very present. I know that sometimes it happens, but now it happens to such an extent that it is almost impossible to test.

Can you try it again please? It's working fine foe me. In which network is this happening?

**Comment by MilanVojnovic95** [comment]
> > This so far that I have tested seems ok to me. However it is very slow and it seems to me that lag is very present. I know that sometimes it happens, but now it happens to such an extent that it is almost impossible to test.
> 
> Can you try it again please? It's working fine foe me. In which network is this happening?


TO me it happens on all networks ... actually on Mainnet my max balance for ETH doesn't work, and it used to work.

**Comment by berteotti** [comment]
> @berteotti To me it happens on all networks ... actually on Mainnet my max balance for ETH doesn't work, and it used to work.

This is my experience. I think it is decent, only on Gnosis Chain there is a slow trade fetching, otherwise it's good. This isn't happening to you?

https://user-images.githubusercontent.com/23079677/163803263-3ea992a2-8937-405a-bc8e-5eee67c050d2.mp4

**Comment by MilanVojnovic95** [comment]
> > @berteotti To me it happens on all networks ... actually on Mainnet my max balance for ETH doesn't work, and it used to work.
> 
> This is my experience. I think it is decent, only on Gnosis Chain there is a slow trade fetching, otherwise it's good. This isn't happening to you?
> 
>  scrnli_18_04_2022_12-40-49.mp4

For some reason this is happening to me but just on Mainnet
image

**Pull request merged**
