### PR TITLE
feature: add Curve to Eco Router

### PR DESCRIPTION
**Pull request by adamazad**
### Summary

Adds [Curve](https://curve.fi), currently with support for

- Gnosis Chain
  - 3pool (WXDAI/USDC/USDT)
- Arbitrum
  - Stable pairs such as 3pool
  - ~~Curve Smart router~~
- ~~Mainnet~~
  - ~~Stable pairs such as 3pool~~
  - ~~Curve Smart router~~

### Notes

This PR uses the [Swapr SDK v1.0.0 Beta 5](https://github.com/levelkdev/dxswap-sdk/releases/tag/v1.0.0-beta.5), which has major changes, and is not compatible with previous `0.x.x` versions.

### CODE REVIEW

**Comment by adamazad** [comment]
Pairs with issues on Mainnet:
- ETH <> stETH
- USDC <>USDT causes division by zero

**Comment by adamazad** [comment]
An issue with estimating input from output amount. 

image

**Comment by MilanVojnovic95** [comment]
If I try with this pair I get this situation
image

And if I choose Curve i get blank page
image

This has been tried with the Meinnet, if it does not support that network it might need to indicate with an error message or something similar.

**Comment by MilanVojnovic95** [comment]
@0xVenky 
 It is displayed on Mainnet, and also there is the old bug
USDC <>USDT causes division by zero but only on mainnet.
 
On Arb1 and gnosis chain everything looks ok.

**Comment by adamazad** [comment]
Closing this due: 

- Found a better implementation.
- Extremely behind `develop`.

**Pull request closed without merging**
