### PR TITLE
swapbox - preselect outputCurrency

### LINKED ISSUE #1445: Swapbox initial state
**Description**
When the user launches swapr.eth.limo, preselect both input and output tokens in the swapbox. Each network will have a predetermined set of tokens and will be used across Simple chart and Pro mode.

image

Mainnet - ETH and DAI
Arbitrum - ETH and USDC
Gnosis Chain - XDAI and GNO
Optimism - ETH and OP
Polygon - ETH and MATIC

#### Definition of done
- [x] Description is created (Task creator)
- [ ] Code is complete (Developer)
- [ ] Scope of test and what was done section is defined in task (Developer)
- [ ] Review passed (Code reviewer)
- [ ] Verified manually (QA)
- [ ] Test cases created/updated if necessary (QA)
- [ ] Change successfully merged
- [ ] Release notes added if needed

**Additional context**
This reduces the different initial states that we might need to have and getting the user what he would like to see in the first glance.

### PR DESCRIPTION
**Pull request by mix1o**
Closes #1445 

## To test
- Check if the output currency is selected automatically on 
`MAINNET`
`GNOSIS`
`ARBITRUM_ONE`
`POLYGON`
`OPTIMISM`

On testnets output currency should not be automatically selected

### CODE REVIEW

**Review by mwiniarsk — APPROVED** [review]

**Review by karczuRF — APPROVED** [review]
lgtm!

**Review by jorgedclopes — APPROVED** [review]

**Review by wixzi — APPROVED** [review]
✨

**Comment by niemam29** [comment]
Tested and looks good

**Comment by MilanVojnovic95** [comment]
Tested and looks ok to me 👍

**Pull request merged**
