### PR TITLE
test: disconnected wallet trade simulation

### PR DESCRIPTION
**Pull request by berteotti**
# Summary

This is just a test PR to see if the fix works when deployed

### CODE REVIEW

**Comment by MilanVojnovic95** [comment]
Tested and related to this https://github.com/levelkdev/swapr-dapp/issues/1099
it still happens that loading for a route but only for a second or two and then it doesn't show any results but the "connect wallet" button.

**Comment by berteotti** [comment]
> Tested and related to this #1099 it still happens that loading for a route but only for a second or two and then it doesn't show any results but the "connect wallet" button.

Tried to replicate that but for me works fine. Here is an example 👇

https://user-images.githubusercontent.com/23079677/176879951-9f3a4110-602e-417f-bb12-ba0b2070156e.mp4

**Comment by berteotti** [comment]
> Tested and related to this #1099 it still happens that loading for a route but only for a second or two and then it doesn't show any results but the "connect wallet" button.

Tried to replicate that but for me works fine. Here is an example 👇

https://user-images.githubusercontent.com/23079677/176880252-b8364734-50e1-45a8-8302-8d1cacc8551e.mp4

**Comment by MilanVojnovic95** [comment]
It's very strange... here's how it is for me when I reproduce

https://user-images.githubusercontent.com/57331244/176881971-29d61fc3-b29d-45f5-ba15-650801472f7e.mp4

**Comment by MilanVojnovic95** [comment]
> It's very strange... here's how it is for me when I reproduce
> 
>  Swapr.01.07.mp4
I found out that this happened because the option to display the exchange list was closed, which should be open by default, this happened only once and after a refresh everything was ok.

**Pull request closed without merging**
